config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get "up" => "rails/health#show", as: :rails_health_check

  resources :categories, only: [:index, :show]
  resources :teddy_types, only: [:index, :show]
  resources :pages, only: [:show]
  resources :orders, only: [:index, :show, :new, :create, :destroy] do
    resources :payments, only: [:new, :create]
  end

  get 'about', to: 'pages#about', as: :about
  get 'contact', to: 'pages#contact', as: :contact

  resource :cart, only: [:show] do
    post 'add_item/:teddy_type_id', to: 'cart_items#create', as: 'add_item'
    delete 'remove_item/:id', to: 'cart_items#destroy', as: 'remove_item'
    patch 'update_item/:id', to: 'cart_items#update', as: 'update_item'
  end

  namespace :admin do
    get 'orders_report', to: 'orders_report#index', as: 'orders_report'
  end

  post 'webhooks/stripe', to: 'webhooks#stripe'

  resources :orders do
    member do
    get :new_payment
  end
end

  root 'teddy_types#index'
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :cart_items, dependent: :destroy
  has_many :teddy_types, through: :cart_items

  def total_price
    cart_items.includes(:teddy_type).sum { |item| item.teddy_type.price * item.quantity }
  end

  def add_teddy_type(teddy_type)
    current_item = cart_items.find_by(teddy_type_id: teddy_type.id)
    if current_item
      current_item.quantity += 1
    else
      current_item = cart_items.build(teddy_type_id: teddy_type.id)
      current_item.quantity = 1
    end
    current_item.save
    current_item
  end

  def remove_teddy_type(teddy_type)
    current_item = cart_items.find_by(teddy_type_id: teddy_type.id)
    if current_item
      current_item.quantity -= 1
      current_item.save
      current_item.destroy if current_item.quantity <= 0
    end
  end

  def clear
    cart_items.destroy_all
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!

  def show
    @cart = current_cart
  end

  def add_item
    @cart = current_cart
    teddy_type = TeddyType.find(params[:teddy_type_id])
    @cart.add_teddy_type(teddy_type)

    redirect_to cart_path(@cart)
  end

  def remove_item
    @cart = current_cart
    teddy_type = TeddyType.find(params[:teddy_type_id])
    @cart.remove_teddy_type(teddy_type)

    redirect_to cart_path(@cart)
  end

  def update_item
    @cart = current_cart
    cart_item = @cart.cart_items.find(params[:cart_item_id])
    cart_item.update(quantity: params[:quantity])

    redirect_to cart_path(@cart)
  end
end

app/views/carts/show.html.erb
<h1>Your Cart</h1>

<% if @cart.cart_items.any? %>
  <ul>
    <% @cart.cart_items.each do |item| %>
      <li>
        <%= item.teddy_type.teddy_name %> - Quantity: <%= item.quantity %> - Price: <%= number_to_currency(item.teddy_type.price) %>
        <%= link_to 'Remove', remove_item_cart_path(item), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
      </li>
    <% end %>
  </ul>
  <p>Total Price: <%= number_to_currency(@cart.total_price) %></p>

  <%= form_with model: @order, url: orders_path, local: true do |form| %>
    <div class="form-group">
      <%= form.label :street %>
      <%= form.text_field :street, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= form.label :city %>
      <%= form.text_field :city, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= form.label :province %>
      <%= form.select :province, options_for_select(Order::PROVINCES), {}, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= form.label :postal_code %>
      <%= form.text_field :postal_code, class: 'form-control' %>
    </div>
    <%= form.submit 'Complete Order', class: 'btn btn-primary' %>
  <% end %>
<% else %>
  <p>Your cart is empty.</p>
<% end %>